name: DP Deploy
on:
  push:
jobs:
  test:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the jar
        run: sbt assembly
      - name: Upload to S3
        run: aws s3 cp target/scala-2.13/preservica-config.jar s3://sandbox-dp-code-deploy/preservica-config.jar
      - name: Update function code
        run:  aws lambda update-function-code --function-name sandbox-deploy-preservica-config --s3-bucket sandbox-dp-code-deploy --s3-key preservica-config.jar
